<?php

namespace JmBatiInterimBundle\Repository;

/**
 * ChefchantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefchantierRepository extends \Doctrine\ORM\EntityRepository
{
}
