<?php

namespace JmBatiInterimBundle\Repository;

/**
 * CorpsmetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorpsmetierRepository extends \Doctrine\ORM\EntityRepository
{
}
